#ifndef GUARD_PLAYS_H
#define GUARD_PLAYS_H

typedef enum {
	PLAY_NONE,

	PLAY_OFF_RUN,
	PLAY_OFF_SHORT_PASS,
	PLAY_OFF_LONG_PASS,
	PLAY_OFF_KNEEL,
	PLAY_OFF_KICK,
	PLAY_OFF_PUNT,

	PLAY_DEF_BASE,
	PLAY_DEF_MAN,
	PLAY_DEF_COVER,
	PLAY_DEF_PREVENT,
	PLAY_DEF_GOAL_LINE,
	PLAY_DEF_BLITZ,

	PLAY_COUNT,

	//Aliases
	
	PLAY_SPECIAL_TEAMS_START = PLAY_OFF_KNEEL,
	PLAY_SPECIAL_TEAMS_END   = PLAY_OFF_PUNT + 1,
	
	PLAY_OFF_START = PLAY_OFF_RUN,
	PLAY_OFF_END   = PLAY_OFF_PUNT + 1,

	PLAY_DEF_START = PLAY_DEF_BASE,
	PLAY_DEF_END   = PLAY_DEF_BLITZ + 1
} PlayID;

constexpr char gPlayStrings[PLAY_COUNT][16] = {
	[PLAY_NONE] = "PLAY NONE";
}

#endif
