#include "team.h"

#include "raylib.h"

#include <string.h>

static const TeamBlueprint sTeamBlueprints[] = {
	[TEAM_NONE] = {
		.id = TEAM_NONE,
		.name = "NONE",
		.rosterSchema = {{ 0 }}

	},
	[TEAM_RANDOM] = {
		.id = TEAM_RANDOM,
		.name = "RANDOM",
		.rosterSchema = {{ 0 }}
	},
	[TEAM_BLACK] = {
		.id = TEAM_BLACK,
		.name = "BLACK",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_TIGHT_END]        = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_WIDE_RECEIVER]    = {3, PLAYER_STAT_MOD_BUFF},
			[POSITION_DEFENSIVE_TACKLE] = {1, PLAYER_STAT_MOD_STAR},
			[POSITION_DEFENSIVE_END]    = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_LINE_BACKER]      = {4, PLAYER_STAT_MOD_BUFF},
			[POSITION_DEFENSIVE_BACK]   = {4, PLAYER_STAT_MOD_BUFF},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_DEBUFF}
		}
	},
	[TEAM_WHITE] = {
		.id = TEAM_WHITE,
		.name = "WHITE",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_STAR},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_TIGHT_END]        = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_WIDE_RECEIVER]    = {3, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_DEFENSIVE_TACKLE] = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_DEFENSIVE_END]    = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_LINE_BACKER]      = {3, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_DEFENSIVE_BACK]   = {4, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_BUFF}
		}
	},
	[TEAM_GREEN] = {
		.id = TEAM_GREEN,
		.name = "GREEN",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_TIGHT_END]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_WIDE_RECEIVER]    = {4, PLAYER_STAT_MOD_BUFF},
			[POSITION_DEFENSIVE_TACKLE] = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_END]    = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_LINE_BACKER]      = {2, PLAYER_STAT_MOD_STAR},
			[POSITION_DEFENSIVE_BACK]   = {5, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
	[TEAM_RED] = {
		.id = TEAM_RED,
		.name = "RED",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_FULL_BACK]        = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_HALF_BACK]        = {1, PLAYER_STAT_MOD_STAR},
			[POSITION_TIGHT_END]        = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_WIDE_RECEIVER]    = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_DEFENSIVE_TACKLE] = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_DEFENSIVE_END]    = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_LINE_BACKER]      = {4, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_DEFENSIVE_BACK]   = {3, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
	[TEAM_PINK] = {
		.id = TEAM_PINK,
		.name = "PINK",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TIGHT_END]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_WIDE_RECEIVER]    = {5, PLAYER_STAT_MOD_STAR},
			[POSITION_DEFENSIVE_TACKLE] = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_DEFENSIVE_END]    = {2, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_LINE_BACKER]      = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_BACK]   = {6, PLAYER_STAT_MOD_BUFF},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
	[TEAM_BROWN] = {
		.id = TEAM_BROWN,
		.name = "BROWN",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_STAR},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_BUFF},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_FULL_BACK]        = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_TIGHT_END]        = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_WIDE_RECEIVER]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_TACKLE] = {4, PLAYER_STAT_MOD_BUFF},
			[POSITION_DEFENSIVE_END]    = {2, PLAYER_STAT_MOD_BUFF},
			[POSITION_LINE_BACKER]      = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_BACK]   = {3, PLAYER_STAT_MOD_DEBUFF},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
	[TEAM_YELLOW] = {
		.id = TEAM_YELLOW,
		.name = "YELLOW",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TIGHT_END]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_WIDE_RECEIVER]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_TACKLE] = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_END]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_LINE_BACKER]      = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_BACK]   = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
	[TEAM_ORANGE] = {
		.id = TEAM_ORANGE,
		.name = "ORANGE",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TIGHT_END]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_WIDE_RECEIVER]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_TACKLE] = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_END]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_LINE_BACKER]      = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_BACK]   = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
	[TEAM_BLUE] = {
		.id = TEAM_BLUE,
		.name = "BLUE",
		.rosterSchema = {
			[POSITION_NONE]             = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TACKLE]           = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_GUARD]            = {2, PLAYER_STAT_MOD_NONE},
			[POSITION_CENTER]           = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_QUARTER_BACK]     = {1, PLAYER_STAT_MOD_NONE},
			[POSITION_FULL_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_HALF_BACK]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_TIGHT_END]        = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_WIDE_RECEIVER]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_TACKLE] = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_END]    = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_LINE_BACKER]      = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_DEFENSIVE_BACK]   = {0, PLAYER_STAT_MOD_NONE},
			[POSITION_KICKER]           = {1, PLAYER_STAT_MOD_NONE}
		}
	},
};


TeamData gTeamData[TEAM_COUNT];

void InitTeamData(void)  
{
	for (int i=0; i<TEAM_COUNT; i++) {
		gTeamData[i].id   = sTeamBlueprints[i].id;
		gTeamData[i].name = sTeamBlueprints[i].name;
		memcpy(gTeamData[i].rosterSchema, sTeamBlueprints[i].rosterSchema, sizeof(sTeamBlueprints[i].rosterSchema));
		//Color
		switch (i) {
			case TEAM_WHITE:
				gTeamData[i].color = WHITE;
				break;
			case TEAM_GREEN:
				gTeamData[i].color = GREEN;
				break;
			case TEAM_RED:
				gTeamData[i].color = RED;
				break;
			case TEAM_PINK:
				gTeamData[i].color = PINK;
				break;
			case TEAM_BROWN:
				gTeamData[i].color = BROWN;
				break;
			case TEAM_YELLOW:
				gTeamData[i].color = YELLOW;
				break;
			case TEAM_ORANGE:
				gTeamData[i].color = ORANGE;
				break;
			case TEAM_BLUE:
				gTeamData[i].color = BLUE;
				break;
			case TEAM_NONE:
			case TEAM_RANDOM:
			case TEAM_BLACK:
			default:
				gTeamData[i].color = BLACK;
				break;
		}
	}
}

const TeamData* GetTeamData(TeamId id)
{
	return &gTeamData[id];
}
